### PR TITLE
Feature/combinatorial cost

### PR DESCRIPTION
**Pull request by Pete-York**
Hi,
Here's the current state of what I have.

I'll give an example use case at some point.

### CODE REVIEW

**Comment by deepcharles** [comment]
Thanks for the pull request. I would like to change a few things though. Before I review the commits, can you give me a write access (which you can revoke later) to the branch " feature/combinatorial-cost" of your fork (see for instance [this link](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork)). That way, I could also add commits to this PR.

**Comment by GuillaumeWrobel** [comment]
hey @deepcharles and @Pete-York 
kudos for the great work! any update on this PR? Would be happy to help you with technical implementation.

**Comment by achab** [comment]
@deepcharles @GuillaumeWrobel any update on this PR ?

**Comment by GuillaumeWrobel** [comment]
> @deepcharles @GuillaumeWrobel any update on this PR ?

It seems that the library is no longer maintained.

**Comment by deepcharles** [comment]
Hello, this library is actively maintained!

For important contributions such as new methods, I'll try as much as possible to have them relate to published articles in academic journals/conferences.
Smaller improvements/bug fixes are obviously welcome!

Closing this PR for now.

**Pull request closed without merging**
