### PR TITLE
Add support of efficient kernel change point detection

### PR DESCRIPTION
**Pull request by oboulant**

### CODE REVIEW

**Comment by oboulant** [comment]
@deepcharles 
Just a reminder to remove from the doc any reference to `requirements.txt`

**Comment by deepcharles** [comment]
Shouldn't it be `M_V[s * (n_bkps + 1) + k-1]` (this is the coefficient (s, k-1) of the matrix M_V) instead of 

https://github.com/deepcharles/ruptures/blob/be0548c1657fd9d0f492f6bbfad03e9d846223eb/ruptures/detection/_detection/ekcpd_computation.c#L86

**Comment by deepcharles** [comment]
the build on windows does not complete. Can you take a look @oboulant ?

**Comment by deepcharles** [comment]
I have removed the use of jump in the kernel dynamic programming because the code was really too complex and added almost not computational gain. Only the min_size remains, because that something user might want to calibrate.

**Comment by deepcharles** [comment]
All that remains is :

- [ ] write some test for pelt

- [ ] make the build succeed on windows

- [ ] add doc for KernelCPD

**Comment by deepcharles** [comment]
I've added a new kernel (cosine) just to see

**Pull request merged**
