### PR TITLE
docs: add text segmentation example

### PR DESCRIPTION
**Pull request by oboulant**

### CODE REVIEW

**Comment by deepcharles** [comment]
I added the corrections I wanted. Check if that is ok with you.

**Comment by deepcharles** [comment]
I do not understand how Github can run the notebooks without us specifying that it needs scikit-learn

**Review by deepcharles — APPROVED** [review]

**Comment by oboulant** [comment]
@deepcharles I added the gram matrix representation. Ca you check if the final result is fine with you ?

**Comment by deepcharles** [comment]
Maybe we should open another PR to do those kind of tests. And revert all changes to the run-test gh action in that current PR.

**Comment by oboulant** [comment]
> Maybe we should open another PR to do those kind of tests. And revert all changes to the run-test gh action in that current PR.

Yes, what I wanted to do as well ! Will proceed with the revert and creation of a new PR for tweaking `run-test.yml` !

**Pull request merged**
