### PR TITLE
refactor: improve speed of BottomUp

### PR DESCRIPTION
**Pull request by probberechts**
This PR makes some small modifications to improve the speed of the BottomUp segmentation algorithm, especially when applied to long time series.

----

Below is a simple benchmark:

```python
import time
import ruptures as rpt

n_samples, n_dims, sigma = 100_000, 1, 2
n_bkps = 100  # number of breakpoints
signal, bkps = rpt.pw_constant(n_samples, n_dims, n_bkps, noise_std=sigma)

t1 = time.perf_counter(), time.process_time()
algo = rpt.BottomUp(model="normal").fit(signal)
my_bkps = algo.predict(n_bkps=100)
t2 = time.perf_counter(), time.process_time()
print(f" Real time: {t2[0] - t1[0]:.2f} seconds")
print(f" CPU time: {t2[1] - t1[1]:.2f} seconds")
```

**Current implementation**: 46.08 seconds                                                                                                                                                                                                                                                       
**Adapted implementation**: 6.94 seconds

### CODE REVIEW

**Comment by oboulant** [comment]
@probberechts Thx for the great work !
Can you push some fake changes : indeed it is strange, your created PR did not trigger the usual automated checks (tests and everything).

**Comment by oboulant** [comment]
This is an example of a recent PR for which I could allow the usual checks to run for a first time contributor : https://github.com/deepcharles/ruptures/pull/315

**Comment by probberechts** [comment]
I don't know why it didn't work, but I think you should be able to run the workflows now.

**Comment by oboulant** [comment]
On my end : 
**Current implementation**: 17.23 seconds
**Adapted implementation**: 1.36 seconds

🚀

**Review by oboulant — APPROVED** [review]
LGTM

**Pull request merged**
