### PR TITLE
ci(pypi): build wheels and sdists and push to pypi

### PR DESCRIPTION
**Pull request by oboulant**

### CODE REVIEW

**Comment by oboulant** [comment]
# https://github.com/deepcharles/ruptures-issues/issues/7

**Review by deepcharles — APPROVED** [review]

**Comment by deepcharles** [comment]
@oboulant merge it if that ok with you

**Comment by deepcharles** [comment]
I forgot to change the trigger events
doing it right now

**Review by deepcharles — APPROVED** [review]

**Comment by deepcharles** [comment]
@oboulant merge it if that ok with you

**Comment by deepcharles** [comment]
close deepcharles/ruptures#83

**Comment by deepcharles** [comment]
close  deepcharles/ruptures-issues#7

**Pull request merged**
