### PR TITLE
build: add support of cp10 and cp11 wheels when possible

### PR DESCRIPTION
**Pull request by oboulant**
This PR adds support for building wheels for cp310 and cp311 when it is possible. 

* `cp311-manylinux_i686` is **not** supported 
* `cp{38,39,310,311}-win32` are **not** supported

Support was also added for `aarch64`. 

`pre-commit-ci-update-config` has already been merged into `ci-py311-wheel` branch !  

closes https://github.com/deepcharles/ruptures/issues/296

### CODE REVIEW

**Comment by oboulant** [comment]
Have to add support for python v3.11 in the tests

**Comment by oboulant** [comment]
> Have to add support for python v3.11 in the tests

Added here : https://github.com/deepcharles/ruptures/pull/299 

https://github.com/deepcharles/ruptures/pull/299 should be merged before this current PR.

**Comment by pbregener** [comment]
Hi @deepcharles!
Any chance you can review this fairly trivial PR (and related #299) soon? And maybe even consider releasing a new version so that one can get wheels for py310+311 directly from pypi?
Thanks :)

PS: Thanks @oboulant for putting this together so nicely and quickly!

**Review by deepcharles — APPROVED** [review]

**Comment by deepcharles** [comment]
Sorry, I totally forgot. No problem for the new version.

**Pull request closed without merging**
